-- Google Play compliance: AI response reports and external account deletion requests.

create table if not exists public.ai_response_reports (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  message_text text not null,
  response_text text not null,
  reason text not null default 'offensive_or_unsafe',
  created_at timestamptz not null default now()
);

alter table public.ai_response_reports enable row level security;

create policy "Users can submit their own AI response reports"
  on public.ai_response_reports for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

create table if not exists public.account_deletion_requests (
  id bigint generated by default as identity primary key,
  email text not null,
  reason text,
  status text not null default 'pending' check (status in ('pending', 'completed', 'rejected')),
  created_at timestamptz not null default now(),
  completed_at timestamptz
);

alter table public.account_deletion_requests enable row level security;

-- No public SELECT/UPDATE/DELETE policies: requests are submitted through the
-- server route using the Supabase service-role key and are not exposed to anon users.
